# Generated by Django 3.2.16 on 2022-12-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_featured_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
