# Generated by Django 3.2.16 on 2022-12-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_owner_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
