# Generated by Django 3.2.16 on 2022-12-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default='0', max_length=2),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
