# Generated by Django 3.2.16 on 2022-12-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('_0', '0'), ('_1', '1'), ('_2', '2'), ('_3', '3'), ('_4', '4'), ('_5', '5'), ('_6', '6'), ('_7', '7'), ('_8', '8'), ('_9', '9'), ('_10', '10')], default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_tag',
            field=models.CharField(choices=[('game', 'Game'), ('film', 'Film'), ('boardgame', 'Boardgame'), ('book', 'Book'), ('tv series', 'Tv Series'), ('blank', 'Blank')], default='blank', max_length=32),
        ),
    ]
